- name: Mysql Setup
  hosts: all
  become: yes
  tasks:
    - name: Install Mysql
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: start mysql server
      ansible.builtin.systemd_service:
        state: started
        enabled: yes

    - name: setup mysql password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
