- name: Install Mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Check if MySQL root password is set
  ansible.builtin.shell: "mysqladmin --user=root --password=ExpenseApp@1 status"
  register: mysql_password_status
  ignore_errors: yes

- name: Set up MySQL root password if not set
  ansible.builtin.shell: >
    mysql_secure_installation --set-root-pass ExpenseApp@1
  when: "'ERROR' in mysql_password_status.stdout"